import React from 'react';
import ArrayToTable from './ArrayToTable';
const sampleData = [
{'Entregas Black': 25834,
  'Entregas Cincita': 2005,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 321,
  'Entregas Pride 2022': 0,
  'Entregas Mundial': 2192,
  'Entregas Pride Hologlam': 0,
  'Entregas Pride Colors': 0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 33271,
  'Entregas Cincita': 0,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0,
  'Entregas Pride Colors': 0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 33543,
  'Entregas Cincita': 0,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0,
  'Entregas Pride Colors': 0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 31594,
  'Entregas Cincita': 0,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 1623.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0,
  'Entregas Pride Colors': 0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 29007,
  'Entregas Cincita': 0,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 2312.0,
  'Entregas Mundial': 1295,
  'Entregas Pride Hologlam': 0,
  'Entregas Pride Colors': 0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 16712,
  'Entregas Cincita': 0,
  'Entregas Onix': 0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 1797,
  'Entregas Pride Hologlam': 1218.0,
  'Entregas Pride Colors': 580.0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 5916,
  'Entregas Cincita': 40,
  'Entregas Onix': 122.0,
  'Entregas Cincita Reemplazo': 16,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 34,
  'Entregas Pride Hologlam': 2387.0,
  'Entregas Pride Colors': 969.0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 5684,
  'Entregas Cincita': 0,
  'Entregas Onix': 529.0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 2184.0,
  'Entregas Pride Colors': 947.0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 6341,
  'Entregas Cincita': 47,
  'Entregas Onix': 688.0,
  'Entregas Cincita Reemplazo': 78,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 713.0,
  'Entregas Pride Colors': 369.0,
  'Entregas Cardlaveritas': 0,
  'Entregas Cardtrinas': 0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 4181,
  'Entregas Cincita': 79,
  'Entregas Onix': 290.0,
  'Entregas Cincita Reemplazo': 121,
  'Entregas Pride 2022': 108.0,
  'Entregas Mundial': 418,
  'Entregas Pride Hologlam': 422.0,
  'Entregas Pride Colors': 366.0,
  'Entregas Cardlaveritas': 2379.0,
  'Entregas Cardtrinas': 118.0,
  'Entregas Cardjolote White': 0,
  'Entregas Cardjolote Black': 0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 3040,
  'Entregas Cincita': 148,
  'Entregas Onix': 307.0,
  'Entregas Cincita Reemplazo': 41,
  'Entregas Pride 2022': 2.0,
  'Entregas Mundial': 472,
  'Entregas Pride Hologlam': 71.0,
  'Entregas Pride Colors': 249.0,
  'Entregas Cardlaveritas': 2803.0,
  'Entregas Cardtrinas': 1249.0,
  'Entregas Cardjolote White': 646.0,
  'Entregas Cardjolote Black': 1491.0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 3736,
  'Entregas Cincita': 139,
  'Entregas Onix': 188.0,
  'Entregas Cincita Reemplazo': 44,
  'Entregas Pride 2022': 9.0,
  'Entregas Mundial': 462,
  'Entregas Pride Hologlam': 63.0,
  'Entregas Pride Colors': 1.0,
  'Entregas Cardlaveritas': 1381.0,
  'Entregas Cardtrinas': 620.0,
  'Entregas Cardjolote White': 3061.0,
  'Entregas Cardjolote Black': 2848.0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 5398,
  'Entregas Cincita': 333,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 99,
  'Entregas Pride 2022': 73.0,
  'Entregas Mundial': 471,
  'Entregas Pride Hologlam': 34.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 2277.0,
  'Entregas Cardtrinas': 653.0,
  'Entregas Cardjolote White': 805.0,
  'Entregas Cardjolote Black': 2882.0,
  'Entregas Ocean Plastic': 0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 4790,
  'Entregas Cincita': 278,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 75,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 77,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 7.0,
  'Entregas Cardlaveritas': 431.0,
  'Entregas Cardtrinas': 267.0,
  'Entregas Cardjolote White': 62.0,
  'Entregas Cardjolote Black': 6176.0,
  'Entregas Ocean Plastic': 1213.0,
  'Entregas PlayCard': 0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 6073,
  'Entregas Cincita': 236,
  'Entregas Onix': 1.0,
  'Entregas Cincita Reemplazo': 97,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 1,
  'Entregas Pride Hologlam': 1.0,
  'Entregas Pride Colors': 28.0,
  'Entregas Cardlaveritas': 235.0,
  'Entregas Cardtrinas': 413.0,
  'Entregas Cardjolote White': 87.0,
  'Entregas Cardjolote Black': 1154.0,
  'Entregas Ocean Plastic': 5292.0,
  'Entregas PlayCard': 1725.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 6371,
  'Entregas Cincita': 256,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 56,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 1.0,
  'Entregas Pride Colors': 4.0,
  'Entregas Cardlaveritas': 6.0,
  'Entregas Cardtrinas': 18.0,
  'Entregas Cardjolote White': 8.0,
  'Entregas Cardjolote Black': 5520.0,
  'Entregas Ocean Plastic': 2385.0,
  'Entregas PlayCard': 3907.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 7887,
  'Entregas Cincita': 416,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 51,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 7.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 13.0,
  'Entregas Cardjolote White': 7.0,
  'Entregas Cardjolote Black': 3750.0,
  'Entregas Ocean Plastic': 2631.0,
  'Entregas PlayCard': 3099.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 2790.0,
  'Entregas Pride 2024': 0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 6926,
  'Entregas Cincita': 320,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 44,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 33,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 1.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 3.0,
  'Entregas Cardjolote White': 62.0,
  'Entregas Cardjolote Black': 172.0,
  'Entregas Ocean Plastic': 3574.0,
  'Entregas PlayCard': 734.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 2975.0,
  'Entregas Pride 2024': 2330.0,
  'Entregas Minion Rayo': 0,
  'Entregas Minion Mega': 0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 7981,
  'Entregas Cincita': 228,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 30,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 39,
  'Entregas Pride Hologlam': 2.0,
  'Entregas Pride Colors': 1.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 6.0,
  'Entregas Cardjolote White': 4.0,
  'Entregas Cardjolote Black': 84.0,
  'Entregas Ocean Plastic': 2996.0,
  'Entregas PlayCard': 188.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 1776.0,
  'Entregas Pride 2024': 3771.0,
  'Entregas Minion Rayo': 1725.0,
  'Entregas Minion Mega': 1267.0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 9155,
  'Entregas Cincita': 182,
  'Entregas Onix': 2.0,
  'Entregas Cincita Reemplazo': 22,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 28,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 1.0,
  'Entregas Cardjolote White': 0.0,
  'Entregas Cardjolote Black': 48.0,
  'Entregas Ocean Plastic': 2066.0,
  'Entregas PlayCard': 3278.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 1232.0,
  'Entregas Pride 2024': 2582.0,
  'Entregas Minion Rayo': 1222.0,
  'Entregas Minion Mega': 918.0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 7257,
  'Entregas Cincita': 251,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 22,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 38,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 1.0,
  'Entregas Cardjolote White': 0.0,
  'Entregas Cardjolote Black': 6157.0,
  'Entregas Ocean Plastic': 2724.0,
  'Entregas PlayCard': 1954.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 284.0,
  'Entregas Pride 2024': 573.0,
  'Entregas Minion Rayo': 687.0,
  'Entregas Minion Mega': 1123.0,
  'Entregas Cardlaveritas 2024': 0,
  'Entregas Wicked': 0},
 {'Entregas Black': 4313,
  'Entregas Cincita': 102,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 27,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 17,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 2.0,
  'Entregas Cardtrinas': 9.0,
  'Entregas Cardjolote White': 9.0,
  'Entregas Cardjolote Black': 3512.0,
  'Entregas Ocean Plastic': 1859.0,
  'Entregas PlayCard': 531.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 108.0,
  'Entregas Pride 2024': 17.0,
  'Entregas Minion Rayo': 269.0,
  'Entregas Minion Mega': 525.0,
  'Entregas Cardlaveritas 2024': 2492.0,
  'Entregas Wicked': 0},
 {'Entregas Black': 4427,
  'Entregas Cincita': 52,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 27,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 7,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 10.0,
  'Entregas Cardtrinas': 7.0,
  'Entregas Cardjolote White': 11.0,
  'Entregas Cardjolote Black': 2490.0,
  'Entregas Ocean Plastic': 2951.0,
  'Entregas PlayCard': 2549.0,
  'Entregas Alebrije': 0,
  'Entregas Gotica': 0.0,
  'Entregas Pride 2024': 19.0,
  'Entregas Minion Rayo': 177.0,
  'Entregas Minion Mega': 90.0,
  'Entregas Cardlaveritas 2024': 4193.0,
  'Entregas Wicked': 1209.0},
 {'Entregas Black': 3468,
  'Entregas Cincita': 0,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 1.0,
  'Entregas Cardtrinas': 1.0,
  'Entregas Cardjolote White': 1.0,
  'Entregas Cardjolote Black': 864.0,
  'Entregas Ocean Plastic': 1945.0,
  'Entregas PlayCard': 1307.0,
  'Entregas Alebrije': 950.0,
  'Entregas Gotica': 25.0,
  'Entregas Pride 2024': 6.0,
  'Entregas Minion Rayo': 124.0,
  'Entregas Minion Mega': 72.0,
  'Entregas Cardlaveritas 2024': 1795.0,
  'Entregas Wicked': 2153.0},
 {'Entregas Black': 2403,
  'Entregas Cincita': 0,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 0.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 2.0,
  'Entregas Cardjolote White': 0.0,
  'Entregas Cardjolote Black': 433.0,
  'Entregas Ocean Plastic': 1343.0,
  'Entregas PlayCard': 14.0,
  'Entregas Alebrije': 3425.0,
  'Entregas Gotica': 19.0,
  'Entregas Pride 2024': 0.0,
  'Entregas Minion Rayo': 82.0,
  'Entregas Minion Mega': 47.0,
  'Entregas Cardlaveritas 2024': 313.0,
  'Entregas Wicked': 767.0},
 {'Entregas Black': 1661,
  'Entregas Cincita': 0,
  'Entregas Onix': 0.0,
  'Entregas Cincita Reemplazo': 0,
  'Entregas Pride 2022': 5.0,
  'Entregas Mundial': 0,
  'Entregas Pride Hologlam': 0.0,
  'Entregas Pride Colors': 0.0,
  'Entregas Cardlaveritas': 0.0,
  'Entregas Cardtrinas': 0.0,
  'Entregas Cardjolote White': 3.0,
  'Entregas Cardjolote Black': 1853.0,
  'Entregas Ocean Plastic': 1135.0,
  'Entregas PlayCard': 329.0,
  'Entregas Alebrije': 2283.0,
  'Entregas Gotica': 18.0,
  'Entregas Pride 2024': 23.0,
  'Entregas Minion Rayo': 31.0,
  'Entregas Minion Mega': 26.0,
  'Entregas Cardlaveritas 2024': 52.0,
  'Entregas Wicked': 308.0}]
;

const Tabla = () => {
  return (
    <div className="container mt-4">
      {/* <h2> <span style = {{color :"Black"}}> Estudiantes </span></h2> */}
      <ArrayToTable data={sampleData} />
    </div>
  );
};

export default Tabla;
